export { default as Home } from './Home'
export { default as AboutPage } from './AboutPage'
export { default as FamilyLawPage } from './FamilyLawPage'
export { default as PersonalInjuryPage } from './PersonalInjuryPage'
export { default as ContactPage } from './ContactPage'
